### ISSUE TITLE
Question: Applying multiple operations in one call to p

### ISSUE THREAD

**Issue by javadba** [sspipe/sspipe#2]
Generally - a great library! The simplifications for usability on Julien's Pipe are important.

The question here is:  I generally define a simple function

` def lmap(x):  return list(map(x))`

This is useful since python3 map,filter, etc return a generator and it is chatty to have list(blah) everywhere to compensate.    But with this sspipe library it does not work: needs to be

 `| p(map) | p(list)`

i.e. the list and map can not be combined into a single invocation of `p`.   We can extrapolate this to be a hassle.   You're a bright guy - can you come up with a solution/workaround to be able to combine multiple operations in one call to `p` ?  Thx!

**Comment by mhsekhavat** [comment]
Thanks for your feedback!

You can use the following solution:

```python
>>> lmap = lambda func: p(lambda x: x | p(map, func) | p(list))
>>> range(3) | lmap(px + 10)
[10, 11, 12]
```
Notice that lmap is a function that receives a func (like `px + 10`) and returns **a new pipe** which maps the func and converts the result to list.

**Comment by mhsekhavat** [comment]
BTW, there is another solution which is more close to your requirement but needs more attention:

```python
>>> def lmap(x, func): return list(map(func, x))
>>> range(3) | lmap(lambda x: x+10)
[10, 11, 12]
```
As you see, it works when called with `lambda x: x+10` function. However, if I pass `px + 10` instead of lambda to it, it will raise:
```python
>>> range(3) | lmap(px + 10)
...
TypeError: unsupported operand type(s) for +: 'range' and 'int'
```
This is because `px+10` will be resolved before it is passed to `lmap` and python cannot evaluate `range(3) + 10`. In order to prevent this early evaluation, you can use `sspipe.unpipe` function to convert the Pipe object to a simple lambda function:

```python
>>> from sspipe import p, px, unpipe
>>> range(3) | lmap(px + 10)
>>> def lmap(x, func): return list(map(func, x))
>>> range(3) | lmap(unpipe(px + 10))
[10, 11, 12]
```
As you see, this became more complicated but worked. The `p(map/filter, func)` function automatically calls `unpipe` on its `func` argument when called with builtin `map`/`filter` values. This is because the first method (`lmap = lambda func: p(map, func) | p(list)`) is more robust.

**Comment by javadba** [comment]
i will make an alias of `unp = unpipe` for other places that `unpipe` may be useful
